"use client";

import { KeyRound } from "lucide-react";
import type { MeResponse } from "@/lib/api/client";

type Props = {
  linked: boolean;
  inboxPubkey?: string;
};

function humanizeStatus(linked: boolean): {
  label: string;
  tone: "ok" | "warn";
} {
  if (linked) return { label: "Linked to your wallet", tone: "ok" };
  return { label: "Not linked yet", tone: "warn" };
}

export function InboxKeyPanel({ linked, inboxPubkey }: Props) {
  const status = humanizeStatus(linked);
  return (
    <section className="radius-surface overflow-hidden border border-border/80 bg-card shadow-card">
      <div className="flex items-start gap-3 border-b border-brand-muted/70 bg-brand-mist px-5 py-4 sm:px-6">
        <span className="flex size-9 shrink-0 items-center justify-center rounded-xl border border-brand-muted bg-brand-soft text-brand-ink">
          <KeyRound className="h-4 w-4" aria-hidden />
        </span>
        <div className="flex min-w-0 flex-1 items-start justify-between gap-3">
          <div>
            <h2 className="text-sm font-semibold text-foreground">Inbox key</h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Encrypted delivery notes use this X25519 public key.
            </p>
          </div>
          <span
            className={
              status.tone === "ok"
                ? "shrink-0 text-xs font-medium text-green-700"
                : "shrink-0 text-xs font-medium text-amber-700"
            }
          >
            {status.label}
          </span>
        </div>
      </div>
      <div className="space-y-3 p-5 sm:p-6 text-sm">
        <p className="text-xs text-muted-foreground">
          The private key stays on this device and is regenerated by signing a
          scoped message with Ready — Wotta never sees it.
        </p>
        {inboxPubkey ? (
          <p className="radius-surface-inner break-all border border-border/70 bg-muted px-4 py-3 text-[11px] text-muted-foreground">
            {inboxPubkey}
          </p>
        ) : null}
      </div>
    </section>
  );
}
